### ISSUE TITLE
Emags don't open doors when equipped in the ID slot.

### ISSUE THREAD

**Issue by AcapitalA** [The-Merchants-Guild/Merchant-Station-13#134]
They used to, but not anymore.
If this is intended, remove them from fitting in the ID slot. If not, someone might want to look into this.

**Comment by TheChosenEvilOne** [comment]
looked into this, it doesn't seem like this ever worked. But Ill make this a feature anyways.

**Comment by eLeCtrOssSnake** [comment]
It never really supposed to work like this. It fits into waller so that you can store/hide it there.

**Comment by karmaisblackandbluepilled** [comment]
On God acap you're so retarded :pray_skin_tone_1:
